project_root: /home/dananday/Research/RIOT

# relative to project_root 
proof_root: cbmc/CodexUP_TestPrompt

# where Makefile.include is found (Provide absolute path)
makefile_include_dir: /home/dananday/Research/CodexUP/templates

# Examples are optional, controlled by a flag (Provide absolute path)
examples_dir: /home/dananday/Research/CodexUP/templates/examples

# relative to project_root
targets:
  - function: _receive
    file_path: sys/net/gnrc/transport_layer/tcp/gnrc_tcp_eventloop.c

  - function: gnrc_pktbuf_add
    file_path: sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c

  - function: auto_init_gnrc_ipv6_static_addr
    file_path: sys/net/gnrc/network_layer/ipv6/static_addr/gnrc_ipv6_static_addr.c